### PR TITLE
fix crash when __NSCFNumber' is force casted to 'NSString'

### PR DESCRIPTION
**Pull request by intrigua**
force casting to desired type causes crash sometimes

### CODE REVIEW

**Comment by tmandry** [comment]
Thanks for this. Do you know what attribute was a different type than expected? Was it called from AXSwift itself or your code? I'd like AXSwift to be a reflection of everything the AX API actually does, so maybe something needs updating.

One reason for the assert is that there are so many layers of optionals, and I want to be able to distinguish "this attribute doesn't exist" from "it wasn't the expected type". So maybe the proper way of doing this is to add another API, without an expected type, and let the user cast it themselves.

**Comment by intrigua** [comment]
Yes, it was an AXValue attribute. In the project where I use AXSwift we track all user-typed text within every app. Sometimes getting string value from the focused element crashes because of casting it to string.

I think it's better to use optional conversion in this case because the returned value is still optional. Thanks for this framework!

**Comment by intrigua** [comment]
Any chance to merge this fix?

**Comment by tmandry** [comment]
@intrigua sorry for the delay. Actually, I re-read the comments and the instructions for dealing with this are in this warning:

```
     /// - warning: This method force-casts the attribute to the desired type, which will abort if
     ///            the cast fails. If you want to check the return type, ask for Any.
```

So if you are unsure of the type of an attribute, use `attribute<Any>()`, and then you'll be able to use a case expression to match the type. This also allows you to differentiate the case of an attribute not existing.

I think crashing the program may be a little extreme for an error in this case, but I also don't want to overload the meaning of a nil return value. I've opened issue #7 with more details on the possibilities, but in short, I'm leaning towards throwing a custom error type.

**Comment by intrigua** [comment]
Ok, thanks for the details. I will switch to Any then. But I still think that force unwrapping before returning optional is a redundant risk of crash.

**Pull request closed without merging**
